### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by abhishekk06** [wangziqi2013/zsim-base#1]
Hi @wangziqi2013 

I just checked out your repo (after struggling with original zSim :( )  and trying to compile. Given below is the error that I am hitting. Can you please suggest what went wrong?

(zsim) zsim-base$ make
Detecting whether pin directory exists...
Found pin-2.14
PINPATH=$HOME/CSE530/zsim-base/pin-2.14 scons
/bin/sh: scons: command not found
make: *** [zsim] Error 127

**Comment by wangziqi2013** [comment]
You need to install scons, which is an automated building tool

On Ubuntu you can just do: sudo apt-get install scons

**Comment by abhishekk06** [comment]
Oh yes. I just realized that I have scons-3 and not scons. Just need to do 1 small change in Makefile to get it compiled.

**Comment by wangziqi2013** [comment]
Sure. Let me know if you experience any peculiar issue while compiling and running zsim.

**Comment by abhishekk06** [comment]
Hitting this https://github.com/wangziqi2013/zsim-base/issues/2 now. Am I missing anything in my setup?
